
export const CREATE_CORPORATION_USER_SUCCESS = "@@CORPORATION/CREATE_CORPORATION_USER_SUCCESS";
export const CREATE_CORPORATION_USER_FAILED = "@@CORPORATION/CREATE_CORPORATION_USER_FAILED";

export const CREATE_CORPORATION_USER_AND_BOOKING_SUCCESS = "@@CORPORATION/CREATE_CORPORATION_USER_AND_BOOKING_SUCCESS";
export const CREATE_CORPORATION_USER_AND_BOOKING_FAILED = "@@CORPORATION/CREATE_CORPORATION_USER_AND_BOOKING_FAILED";

export const UPDATE_CORPORATION_USER_SUCCESS = "@@CORPORATION/UPDATE_CORPORATION_USER_SUCCESS";
export const UPDATE_CORPORATION_USER_FAILED = "@@CORPORATION/UPDATE_CORPORATION_USER_FAILED";

export const DELETE_CORPORATION_USER_SUCCESS = "@@CORPORATION/DELETE_CORPORATION_USER_SUCCESS";
export const DELETE_CORPORATION_USER_FAILED = "@@CORPORATION/DELETE_CORPORATION_USER_FAILED";

export const CHANGE_CORPORATION_PASSWORD_SUCCESS = "@@CORPORATION/CHANGE_CORPORATION_PASSWORD_SUCCESS";
export const CHANGE_CORPORATION_PASSWORD_FAILED = "@@CORPORATION/CHANGE_CORPORATION_PASSWORD_FAILED";

export const CHANGE_PAGE = "@@CORPORATION/CHANGE_PAGE";
