
export const LOGIN_CORPORATION_SUCCESS = "LOGIN_CORPORATION_SUCCESS";
export const LOGIN_CORPORATION_FAILED = "LOGIN_CORPORATION_FAILED";

export const LOGOUT_CORPORATION_SUCCESS = "LOGOUT_CORPORATION_SUCCESS";
export const LOGOUT_CORPORATION_FAILED = "LOGOUT_CORPORATION_FAILED";

