
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAILED = "CREATE_BOOKING_FAILED";

export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS";
export const DELETE_BOOKING_FAILED = "DELETE_BOOKING_FAILED";

export const UPDATE_BOOKING_SUCCESS = "UPDATE_BOOKING_SUCCESS";
export const UPDATE_BOOKING_FAILED = "UPDATE_BOOKING_FAILED";

export const LOAD_ALL_BOOKINGS_SUCCESS = "LOAD_ALL_BOOKINGS_SUCCESS";
export const LOAD_ALL_BOOKINGS_FAILED = "LOAD_ALL_BOOKINGS_FAILED";

export const LOAD_CORPORATION_BOOKINGS_SUCCESS = "LOAD_CORPORATION_BOOKINGS_SUCCESS";
export const LOAD_CORPORATION_BOOKINGS_FAILED = "LOAD_CORPORATION_BOOKINGS_FAILED";


export const SHOW_FULL_CREATE_BOOKING_PAGE = "SHOW_FULL_CREATE_BOOKING_PAGE";
export const HIDE_FULL_CREATE_BOOKING_PAGE = "HIDE_FULL_CREATE_BOOKING_PAGE";

export const SELECT_BOOKING_SUCCESS = "SELECT_BOOKING_SUCCESS";
